insert into regiones (id, nombre) values (1, 'Lithuania');
insert into regiones (id, nombre) values (2, 'Greece');
insert into regiones (id, nombre) values (3, 'China');
insert into regiones (id, nombre) values (4, 'Indonesia');
insert into regiones (id, nombre) values (5, 'Brazil');
insert into regiones (id, nombre) values (6, 'Philippines');
insert into regiones (id, nombre) values (7, 'Nigeria');
insert into regiones (id, nombre) values (8, 'Philippines');
insert into regiones (id, nombre) values (9, 'Israel');
insert into regiones (id, nombre) values (10, 'Georgia');

insert into clientes (nombre, apellido, email, create_at, region_id) values ('Jaime', 'Blackaller', 'jblackaller0@cisco.com', '2022-05-04',10);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Stephanie', 'Jakobssen', 'sjakobssen1@bizjournals.com', '2021-08-27',9);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Heda', 'Maharey', 'hmaharey2@fema.gov', '2021-12-11',8);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Trumaine', 'Dybell', 'tdybell3@yellowpages.com', '2021-07-14',7);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Leo', 'Laughren', 'llaughren4@1und1.de', '2022-04-15',6);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Ailyn', 'Corkel', 'acorkel5@webs.com', '2021-07-31',5);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Yehudit', 'Regis', 'yregis6@va.gov', '2021-07-04',4);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Jeramie', 'Pallister', 'jpallister7@livejournal.com', '2022-01-12',3);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Nils', 'Wile', 'nwile8@senate.gov', '2021-12-10',2);
insert into clientes (nombre, apellido, email, create_at, region_id) values ('Tana', 'Hassin', 'thassin9@meetup.com', '2021-05-10',1);
